[web]
# Public IP from: terraform -chdir=02-terraform/infra/envs/dev output -raw vm_public_ip
webserver ansible_host=54.162.216.95 ansible_user=ubuntu ansible_ssh_private_key_file=/mnt/c/Users/ilyas/.ssh/tp-terraform-dev-ed25519 ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new'
