name: TF Format Check

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  check-tf-format:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6.0.2

      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.15.9"

      - name: Check Terraform formatting
        working-directory: 02-terraform
        run: make tf.fmt.ci
